# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Advanced Roofing Cntractors
email: info@advancedroofing.com.au
description: Roofing and cladding specialists
keywords: Advanced Roofing Contractors, Roofing, Roof Plumbing, Contracting, Sheeting, David Hargreaves, Alice Hargreaves, Cladding
baseurl: ""
url: "http://www.advancedroofingcontractors.com.au/" 
github_username: Elbone

# Build settings
markdown: kramdown
sass:
  style: compressed


# Content settings
collections:
  - gallery
